# Generated by Django 4.2.15 on 2024-08-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=100, unique=True)),
                ('position_id', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=100)),
            ],
        ),
    ]
